# Generated by Django 4.2.3 on 2023-08-18 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import index.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('colegio', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=200)),
                ('tipo_colegio', models.CharField(max_length=200, null=True)),
                ('cont_cotizacion', models.IntegerField(default=0)),
                ('cont_ventaA', models.IntegerField(default=0)),
                ('cont_ventaC', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Costos_fijos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('archivo', models.FileField(null=True, upload_to='')),
                ('fecha', models.DateField()),
                ('impuesto', models.IntegerField(null=True)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Costos_variables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('archivo', models.FileField(null=True, upload_to='')),
                ('fecha', models.DateField()),
                ('impuesto', models.IntegerField(null=True)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.IntegerField(default=0)),
                ('aceptado', models.BooleanField(default=False)),
                ('rechazado', models.BooleanField(default=False)),
                ('venta', models.BooleanField(default=False)),
                ('email_enviado', models.BooleanField(default=False)),
                ('abierta', models.BooleanField(default=False)),
                ('cerrada', models.BooleanField(default=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
                ('precio', models.IntegerField()),
                ('profesional', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('abierta', models.BooleanField(default=True)),
                ('cerrada', models.BooleanField(default=False)),
                ('estado_encuesta', models.BooleanField(default=False)),
                ('total', models.IntegerField(default=0)),
                ('deuda', models.IntegerField(default=0)),
                ('cotizacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='index.cotizacion')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(default=index.models.get_default_profile_image, null=True, upload_to='profile_images/')),
                ('rut', models.CharField(max_length=100, null=True)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('apellidop', models.CharField(max_length=100, null=True)),
                ('apellidom', models.CharField(max_length=100, null=True)),
                ('direccion', models.CharField(max_length=100, null=True)),
                ('comuna', models.CharField(max_length=100, null=True)),
                ('correo', models.EmailField(max_length=100, null=True)),
                ('telefono', models.IntegerField(null=True)),
                ('profesion', models.CharField(max_length=100, null=True)),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('contacto_emergencia', models.IntegerField(null=True)),
                ('nombre_emergencia', models.CharField(max_length=100, null=True)),
                ('parentesco_emergencia', models.CharField(max_length=100, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(upload_to='')),
                ('total', models.IntegerField()),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('numero_factura', models.IntegerField()),
                ('archivo', models.FileField(upload_to='')),
                ('total', models.IntegerField()),
                ('factura_enviada', models.BooleanField(default=False)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='')),
                ('descripcion', models.CharField(max_length=100)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.perfilusuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('descuento', models.IntegerField()),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.cotizacion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='DatosTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_nombre', models.CharField(max_length=100, null=True)),
                ('d_rut', models.CharField(max_length=100, null=True)),
                ('d_correo', models.EmailField(max_length=100, null=True)),
                ('d_banco', models.CharField(max_length=100, null=True)),
                ('d_tipo_cuenta', models.CharField(max_length=100, null=True)),
                ('d_numero_cuenta', models.CharField(max_length=100, null=True)),
                ('d_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Boleta_Honorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(null=True)),
                ('archivo', models.FileField(null=True, upload_to='')),
                ('total', models.IntegerField()),
                ('cantidad_evaluaciones', models.IntegerField(null=True)),
                ('retencion', models.IntegerField(null=True)),
                ('fecha', models.DateField()),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.perfilusuario')),
            ],
        ),
    ]
